// <auto-generated />
using Encoo.LowCode.WechatServer.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Encoo.LowCode.WechatServer.Migrations
{
    [DbContext(typeof(WechatServerDataContext))]
    [Migration("20210114060005_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Encoo.LowCode.WechatServer.Metadata.WechatCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WechatCaches");
                });

            modelBuilder.Entity("Encoo.LowCode.WechatServer.Metadata.WechatPermanentCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CorpId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermanentCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuiteId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WechatPermanentCodes");
                });

            modelBuilder.Entity("Encoo.LowCode.WechatServer.Metadata.WechatSessionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Corpid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Userid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WechatSessionInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
